import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';
import { createKategoriPekerjaan, toggleKategoriPekerjaan } from './kategori-actions';

type SearchParams = Promise<{ error?: string; success?: string }>;

export default async function MasterKategoriPekerjaanPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login');
  const { data, error } = await supabase.from('master_kategori_pekerjaan').select('id_kategori, nama_kategori, urutan, status_aktif').order('urutan');
  const rows = data ?? [];
  const pageError = params.error ?? error?.message;
  return <main style={{minHeight:'100vh',background:'#f6f8fc',color:'#0f172a'}}>
    <header style={header}><div><Link href="/dashboard" style={back}>← Dashboard</Link><div style={brand}>KAVIO</div><div style={title}>Master Kategori Pekerjaan</div></div><div style={{textAlign:'right',fontSize:13,color:'#64748b'}}><div>{user.email}</div><form action="/auth/signout" method="post"><button type="submit" style={logout}>Keluar</button></form></div></header>
    <section style={{padding:28,maxWidth:1180,margin:'0 auto'}}><div style={{marginBottom:22}}><h1 style={{margin:'0 0 6px',fontSize:28}}>Data Kategori Pekerjaan</h1><p style={{margin:0,color:'#64748b'}}>Master kategori pekerjaan untuk konfigurasi bobot progress SPK.</p></div>
      {pageError && <div style={alertError}>{pageError}</div>}{params.success && <div style={alertSuccess}>{params.success}</div>}
      <section style={card}><div style={sectionTitle}>Tambah Kategori Pekerjaan</div><form action={createKategoriPekerjaan} style={{display:'grid',gridTemplateColumns:'1fr 2fr 1fr',gap:12,padding:18}}><Field name="id_kategori" label="ID Kategori" placeholder="KP11"/><Field name="nama_kategori" label="Nama Kategori" placeholder="Pekerjaan Sanitair"/><NumberField name="urutan" label="Urutan" placeholder="11"/><div style={{gridColumn:'1 / -1',textAlign:'right'}}><button type="submit" style={primaryButton}>+ Simpan Kategori</button></div></form></section>
      <section style={{...card,marginTop:20,overflow:'hidden'}}><div style={sectionTitle}>Daftar Kategori ({rows.length})</div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead><tr style={{background:'#f8fafc',textAlign:'left'}}><th style={th}>Urutan</th><th style={th}>ID</th><th style={th}>Nama Kategori</th><th style={th}>Status</th><th style={th}>Aksi</th></tr></thead><tbody>{rows.map(row=><tr key={row.id_kategori}><td style={td}>{row.urutan}</td><td style={tdStrong}>{row.id_kategori}</td><td style={td}>{row.nama_kategori}</td><td style={td}><span style={row.status_aktif?activeBadge:inactiveBadge}>{row.status_aktif?'AKTIF':'NONAKTIF'}</span></td><td style={td}><form action={toggleKategoriPekerjaan}><input type="hidden" name="id_kategori" value={row.id_kategori}/><input type="hidden" name="status_aktif" value={String(row.status_aktif)}/><button type="submit" style={row.status_aktif?outlineButton:primaryMini}>{row.status_aktif?'Nonaktifkan':'Aktifkan'}</button></form></td></tr>)}{!rows.length&&<tr><td colSpan={5} style={{...td,textAlign:'center',padding:34,color:'#64748b'}}>Belum ada data kategori pekerjaan.</td></tr>}</tbody></table></div></section>
    </section></main>;
}
function Field({name,label,placeholder}:{name:string;label:string;placeholder:string}){return <label style={labelStyle}><span>{label}</span><input name={name} placeholder={placeholder} required style={inputStyle}/></label>}
function NumberField({name,label,placeholder}:{name:string;label:string;placeholder:string}){return <label style={labelStyle}><span>{label}</span><input type="number" name={name} placeholder={placeholder} min="1" step="1" required style={inputStyle}/></label>}
const header={background:'#fff',borderBottom:'1px solid #e2e8f0',padding:'16px 28px',display:'flex',justifyContent:'space-between',alignItems:'center'};
const back={textDecoration:'none',color:'#64748b',fontSize:13}; const brand={marginTop:8,fontSize:12,fontWeight:800,letterSpacing:1.5,color:'#2563eb'}; const title={fontSize:21,fontWeight:800}; const logout={border:0,background:'transparent',color:'#2563eb',fontWeight:700,cursor:'pointer'};
const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:16,boxShadow:'0 6px 18px rgba(15,23,42,0.04)'}; const sectionTitle={padding:'16px 18px',borderBottom:'1px solid #e2e8f0',fontWeight:800}; const labelStyle={display:'flex',flexDirection:'column' as const,gap:7,fontSize:12,fontWeight:700,color:'#475569'}; const inputStyle={width:'100%',boxSizing:'border-box' as const,border:'1px solid #cbd5e1',borderRadius:9,padding:'10px 11px',fontSize:14,background:'#fff',color:'#0f172a'}; const primaryButton={background:'#2563eb',color:'#fff',border:0,borderRadius:9,padding:'11px 16px',fontWeight:800,cursor:'pointer'}; const primaryMini={background:'#2563eb',color:'#fff',border:0,borderRadius:8,padding:'7px 10px',fontWeight:700,cursor:'pointer'}; const outlineButton={background:'#fff',color:'#475569',border:'1px solid #cbd5e1',borderRadius:8,padding:'7px 10px',fontWeight:700,cursor:'pointer'}; const th={padding:'12px 14px',borderBottom:'1px solid #e2e8f0',whiteSpace:'nowrap'}; const td={padding:'13px 14px',borderBottom:'1px solid #f1f5f9'}; const tdStrong={...td,fontWeight:800}; const activeBadge={display:'inline-block',background:'#dcfce7',color:'#166534',padding:'4px 8px',borderRadius:999,fontSize:11,fontWeight:800}; const inactiveBadge={display:'inline-block',background:'#f1f5f9',color:'#64748b',padding:'4px 8px',borderRadius:999,fontSize:11,fontWeight:800}; const alertError={background:'#fef2f2',border:'1px solid #fecaca',color:'#991b1b',padding:12,borderRadius:10,marginBottom:14}; const alertSuccess={background:'#f0fdf4',border:'1px solid #bbf7d0',color:'#166534',padding:12,borderRadius:10,marginBottom:14};
