'use client';
import {useEffect,useState} from 'react';
import {createClient} from '../../lib/supabase/client';
import KavioDataTable from '../components/KavioDataTable';
import KavioTableControls from '../components/KavioTableControls';
import {formatKavioDate} from '../lib/date-format';
import {formatKavioMoney} from '../lib/number-format';
type Row={id_baris:string;nomor:string;tanggal:string;jenis_transaksi:string;status:string;nama_pemasok:string|null;no_nota:string|null;lokasi:string;nama_material:string;kategori:string;satuan:string;jumlah:number;jumlah_dipenuhi:number|null;harga_satuan:number|null;nilai:number|null;biaya_dibebankan:number|null};
export default function MaterialReport({suppliers,locations,categories,today}:{suppliers:{id_pemasok:string;nama_pemasok:string}[];locations:{id:string;name:string}[];categories:string[];today:string}) {
 const [kind,setKind]=useState('PEMBELIAN'),[from,setFrom]=useState(today.slice(0,7)+'-01'),[to,setTo]=useState(today),[supplier,setSupplier]=useState(''),[location,setLocation]=useState(''),[category,setCategory]=useState('');
 const [filters,setFilters]=useState({kind:'PEMBELIAN',from:today.slice(0,7)+'-01',to:today,supplier:'',location:'',category:''}),[page,setPage]=useState(0),[rows,setRows]=useState<Row[]>([]),[count,setCount]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let stale=false;async function read(){setBusy(true);setError('');
  let query=createClient().from('v_material_report_detail').select('*',{count:'exact'}).gte('tanggal',filters.from).lte('tanggal',filters.to).order('tanggal',{ascending:false}).order('nomor',{ascending:false}).order('id_baris');
  if(filters.kind==='PEMAKAIAN') query=query.eq('status','POSTED').or('jenis_transaksi.in.(PEMAKAIAN_LANGSUNG,PEMAKAIAN_DARI_SPK,PEMAKAIAN_SUPPLIER_LANGSUNG,REKONSILIASI_KELUAR),and(jenis_transaksi.in.(PENERIMAAN_SPK,KELUAR_KE_SPK),biaya_dibebankan.gt.0)');
  else if(filters.kind) query=query.eq('jenis_laporan',filters.kind);
  if(filters.supplier)query=query.eq('id_pemasok',filters.supplier);
  if(filters.location)query=query.contains('lokasi_ids',[filters.location]);
  if(filters.category)query=query.eq('kategori',filters.category);
  const result=await query.range(page*50,page*50+49);if(stale)return;setRows((result.data??[]) as Row[]);setCount(result.count??0);setError(result.error?.message??'');setBusy(false);
 }read().catch(e=>{if(!stale){setError(e instanceof Error?e.message:'Laporan tidak dapat dibaca.');setBusy(false);}});return()=>{stale=true;};},[filters,page]);
 const qty=(v:number)=>Number(v).toLocaleString('id-ID',{maximumFractionDigits:3});
 return <section className="kavio-panel"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">LAPORAN GUDANG & MATERIAL</h2><p className="kavio-panel-note">Riwayat lengkap, 50 rincian material per halaman. Filter pemasok mengikuti pemasok yang tercatat pada transaksi.</p></div></div>
 <form onSubmit={e=>{e.preventDefault();if(from>to){setError('Periode awal harus sebelum atau sama dengan periode akhir.');return;}setFilters({kind,from,to,supplier,location,category});setPage(0);}}><KavioTableControls count={count} page={page} onPage={setPage} busy={busy}>
 <label className="kavio-field"><span>JENIS LAPORAN</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">SEMUA TRANSAKSI</option>{['PEMBELIAN','PERMINTAAN','PEMAKAIAN','REKONSILIASI','MUTASI'].map(k=><option key={k} value={k}>{k}</option>)}</select></label><label className="kavio-field"><span>DARI TANGGAL</span><input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="kavio-field"><span>SAMPAI TANGGAL</span><input type="date" required value={to} onChange={e=>setTo(e.target.value)}/></label>
 <label className="kavio-field"><span>LOKASI / SPK</span><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">SEMUA LOKASI</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="kavio-field"><span>PEMASOK</span><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">SEMUA PEMASOK</option>{suppliers.map(s=><option key={s.id_pemasok} value={s.id_pemasok}>{s.nama_pemasok}</option>)}</select></label><label className="kavio-field"><span>KATEGORI</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">SEMUA KATEGORI</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label><button className="kavio-button" type="submit" disabled={busy}>TAMPILKAN</button></KavioTableControls></form>
 {error&&<div className="kavio-alert error" role="alert">{error}</div>}
 <KavioDataTable label="Laporan material lengkap" minWidth="1280px" columns={[{key:'date',label:'TANGGAL',width:'8%'},{key:'doc',label:'NOMOR / JENIS',width:'16%'},{key:'location',label:'LOKASI',width:'13%'},{key:'supplier',label:'PEMASOK / NOTA',width:'12%'},{key:'material',label:'MATERIAL / KATEGORI',width:'18%'},{key:'qty',label:'VOLUME',align:'right',width:'9%'},{key:'price',label:'HARGA SATUAN',align:'right',width:'9%'},{key:'value',label:filters.kind==='PEMAKAIAN'?'BIAYA DIBEBANKAN':'NILAI',align:'right',width:'9%'},{key:'status',label:'STATUS',width:'6%'}]}>{rows.map(r=><tr key={r.id_baris}><td>{formatKavioDate(r.tanggal)}</td><td>{r.nomor}<small className="material-subtext">{r.jenis_transaksi.replaceAll('_',' ')}</small></td><td>{r.lokasi||'—'}</td><td>{r.nama_pemasok??'—'}{r.no_nota&&<small className="material-subtext">{r.no_nota}</small>}</td><td>{r.nama_material}<small className="material-subtext">{r.kategori}</small></td><td className="kavio-number">{qty(r.jumlah)} {r.satuan}{r.jumlah_dipenuhi!=null&&<small className="material-subtext">Dipenuhi: {qty(r.jumlah_dipenuhi)}</small>}</td><td className="kavio-number">{r.harga_satuan==null?'—':formatKavioMoney(r.harga_satuan)}</td><td className="kavio-number">{(filters.kind==='PEMAKAIAN'?r.biaya_dibebankan:r.nilai)==null?'—':formatKavioMoney(filters.kind==='PEMAKAIAN'?r.biaya_dibebankan:r.nilai)}</td><td>{r.status.replaceAll('_',' ')}</td></tr>)}{!rows.length&&<tr><td className="kavio-empty" colSpan={9}>{busy?'MEMUAT LAPORAN…':'TIDAK ADA TRANSAKSI SESUAI FILTER.'}</td></tr>}</KavioDataTable></section>;
}
