'use client';
import {useEffect,useState} from 'react';
import {createClient} from '../../lib/supabase/client';
import KavioDataTable from '../components/KavioDataTable';
import KavioTableControls from '../components/KavioTableControls';
import {formatKavioMoney} from '../lib/number-format';
type ConsumerRow={id_sales:string;id_kavling:string;nama_konsumen:string;jenis_pembayaran:string;status_sales:string;total_tagihan:number;total_pelunasan_konsumen:number;saldo_piutang:number};
type BankRow={id_jaminan:string;id_kavling:string;nama_konsumen:string;nama_bank_kpr:string|null;jenis_item:string;nominal_tagihan:number;nominal_diterima:number;saldo_piutang_bank:number;status:string};
export default function ReceivableReport({mode,banks=[]}:{mode:'piutang'|'jaminan';banks?:{id_bank:string;nama_bank:string}[]}){
 const [payment,setPayment]=useState(''),[bank,setBank]=useState(''),[kind,setKind]=useState('');
 const [filters,setFilters]=useState({payment:'',bank:'',kind:''}),[page,setPage]=useState(0),[count,setCount]=useState(0),[rows,setRows]=useState<(ConsumerRow|BankRow)[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let stale=false;async function read(){setBusy(true);setError('');setRows([]);
 let query=mode==='piutang'?createClient().from('v_sales_financial_position').select('id_sales,id_kavling,nama_konsumen,jenis_pembayaran,status_sales,total_tagihan,total_pelunasan_konsumen,saldo_piutang',{count:'exact'}).eq('status_aktif',true).neq('status_sales','BATAL').order('id_kavling').order('id_sales'):createClient().from('v_sales_bank_receivable_report').select('id_jaminan,id_kavling,nama_konsumen,nama_bank_kpr,jenis_item,nominal_tagihan,nominal_diterima,saldo_piutang_bank,status',{count:'exact'}).order('nama_bank_kpr').order('id_kavling').order('jenis_item').order('id_jaminan');
 if(mode==='piutang'&&filters.payment)query=query.eq('jenis_pembayaran',filters.payment);
 if(mode==='jaminan'&&filters.bank)query=query.eq('id_bank_kpr',filters.bank);
 if(mode==='jaminan'&&filters.kind)query=query.eq('jenis_item',filters.kind);
 const result=await query.range(page*50,page*50+49);if(stale)return;setRows(result.data??[]);setCount(result.count??0);setError(result.error?.message??'');setBusy(false);
 }read().catch(e=>{if(!stale){setError(e instanceof Error?e.message:'Laporan tidak dapat dibaca.');setBusy(false);}});return()=>{stale=true;};},[mode,filters,page]);
 const consumerRows=rows as ConsumerRow[];const bankRows=rows as BankRow[];
 const due=rows.reduce((sum,r)=>sum+Number(mode==='piutang'?(r as ConsumerRow).saldo_piutang:(r as BankRow).saldo_piutang_bank),0);
 return <section className="kavio-panel"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">{mode==='piutang'?'LAPORAN PIUTANG':'LAPORAN PIUTANG DANA JAMINAN'}</h2><p className="kavio-panel-note">{mode==='piutang'?'Posisi piutang konsumen saat ini. Pelunasan KPR menggunakan nilai bruto, termasuk piutang yang dialihkan ke bank.':'Posisi dana jaminan saat ini berdasarkan bank pemberi KPR, bukan rekening penerimaan.'} Termasuk saldo nol, 50 baris per halaman.</p></div></div>
 <form onSubmit={e=>{e.preventDefault();setFilters({payment,bank,kind});setPage(0);}}><KavioTableControls count={count} page={page} onPage={setPage} busy={busy}>
 {mode==='piutang'?<label className="kavio-field"><span>KATEGORI PEMBAYARAN</span><select name="payment" value={payment} onChange={e=>setPayment(e.target.value)}><option value="">SEMUA PEMBAYARAN</option><option value="CASH">CASH</option><option value="CASH_BERTAHAP">CASH BERTAHAP</option><option value="KPR">KPR</option></select></label>:<><label className="kavio-field"><span>BANK KPR</span><select name="bank" value={bank} onChange={e=>setBank(e.target.value)}><option value="">SEMUA BANK</option>{banks.map(b=><option key={b.id_bank} value={b.id_bank}>{b.nama_bank}</option>)}</select></label><label className="kavio-field"><span>JENIS DANA JAMINAN</span><select name="guarantee_kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="">SEMUA JENIS</option>{['IMB','SERTIFIKAT','AIR_LISTRIK','BESTEK','GLOBAL'].map(k=><option key={k} value={k}>{k.replaceAll('_',' & ')}</option>)}</select></label></>}
 <button className="kavio-button" type="submit" disabled={busy}>TAMPILKAN</button></KavioTableControls></form>
 {error&&<div className="kavio-alert error" role="alert">{error}</div>}
 {mode==='piutang'?<KavioDataTable label="Laporan piutang konsumen" minWidth="900px" columns={[{key:'lot',label:'KAVLING',width:'9%'},{key:'customer',label:'KONSUMEN',width:'23%'},{key:'payment',label:'PEMBAYARAN',width:'14%'},{key:'status',label:'STATUS SALES',width:'12%'},{key:'bill',label:'TOTAL TAGIHAN',align:'right',width:'14%'},{key:'settled',label:'PELUNASAN KONSUMEN',align:'right',width:'14%'},{key:'balance',label:'SALDO PIUTANG',align:'right',width:'14%'}]}>{consumerRows.map(r=><tr key={r.id_sales}><td>{r.id_kavling}</td><td>{r.nama_konsumen}</td><td>{r.jenis_pembayaran.replaceAll('_',' ')}</td><td>{r.status_sales.replaceAll('_',' ')}</td><td className="kavio-number">{formatKavioMoney(r.total_tagihan)}</td><td className="kavio-number">{formatKavioMoney(r.total_pelunasan_konsumen)}</td><td className="kavio-number">{formatKavioMoney(r.saldo_piutang)}</td></tr>)}{!rows.length&&<tr><td colSpan={7} className="kavio-empty">{busy?'MEMUAT LAPORAN…':'TIDAK ADA PIUTANG SESUAI FILTER.'}</td></tr>}</KavioDataTable>:<KavioDataTable label="Laporan piutang dana jaminan" minWidth="1100px" columns={[{key:'lot',label:'KAVLING',width:'7%'},{key:'customer',label:'KONSUMEN',width:'17%'},{key:'bank',label:'BANK KPR',width:'12%'},{key:'kind',label:'JENIS JAMINAN',width:'13%'},{key:'bill',label:'TAGIHAN JAMINAN',align:'right',width:'13%'},{key:'received',label:'SUDAH DICAIRKAN',align:'right',width:'13%'},{key:'balance',label:'SALDO PIUTANG BANK',align:'right',width:'13%'},{key:'status',label:'STATUS',width:'12%'}]}>{bankRows.map(r=><tr key={r.id_jaminan}><td>{r.id_kavling}</td><td>{r.nama_konsumen}</td><td>{r.nama_bank_kpr??'—'}</td><td>{r.jenis_item.replaceAll('_',' & ')}</td><td className="kavio-number">{formatKavioMoney(r.nominal_tagihan)}</td><td className="kavio-number">{formatKavioMoney(r.nominal_diterima)}</td><td className="kavio-number">{formatKavioMoney(r.saldo_piutang_bank)}</td><td>{r.status.replaceAll('_',' ')}</td></tr>)}{!rows.length&&<tr><td colSpan={8} className="kavio-empty">{busy?'MEMUAT LAPORAN…':'TIDAK ADA DANA JAMINAN SESUAI FILTER.'}</td></tr>}</KavioDataTable>}
 {!busy&&!error&&<div className="kavio-table-pagination"><span>Subtotal saldo pada halaman ini</span><strong className="kavio-number">{formatKavioMoney(due)}</strong></div>}
 </section>;
}
