'use client';
import {useState} from 'react';
import KavioFormActions from '../components/KavioFormActions';
import KavioMaterialLines from '../components/KavioMaterialLines';
import KavioActionGate from '../components/KavioActionGate';
import KavioTransactionModal from '../components/KavioTransactionModal';
import {createMaterialRequest,issueMaterialToSpk,postDirectMaterialUsage,postMaterialReceipt,postSpkMaterialUsage,reconcileSpkMaterial} from './actions';
import type {PurchaseOptions} from './PurchaseForm';
type RequestLine={id_permintaan:string;no_permintaan:string;id_spk:string;id_material:string;nama_material:string;satuan:string;sisa:number};
type StockLine={id_spk:string;id_material:string;nama_material:string;satuan:string;jumlah:number};
export default function MaterialActionPanel({materials,locations,spks,requestLines,spkStocks,mode}:PurchaseOptions&{mode:'saldo'|'pemakaian';requestLines:RequestLine[];spkStocks:StockLine[]}) {
 const [issueMode,setIssueMode]=useState('true');
 const [request,setRequest]=useState(''),[useSpk,setUseSpk]=useState(''),[reconcileSpk,setReconcileSpk]=useState(''),[action,setAction]=useState('KEMBALI_KE_GUDANG');
 const bahan=materials.filter(m=>m.jenis_item==='BAHAN');
 const labelSpk=(id:string)=>{const s=spks.find(s=>s.id_spk===id);return s?`${s.jenis_spk} · ${s.id_kavling??s.nama_objek}`:id;};
 const spkField=(name='id_spk',controlled?:{value:string;change:(v:string)=>void})=><label className="kavio-field material-wide"><span>SPK / OBJEK</span><select name={name} required {...(controlled?{value:controlled.value,onChange:(e:React.ChangeEvent<HTMLSelectElement>)=>controlled.change(e.target.value)}:{defaultValue:''})}><option value="" disabled>PILIH SPK</option>{spks.map(s=><option key={s.id_spk} value={s.id_spk}>{labelSpk(s.id_spk)}</option>)}</select></label>;
 const warehouseField=(name='id_lokasi')=><label className="kavio-field"><span>GUDANG</span><select name={name} required defaultValue=""><option value="" disabled>PILIH GUDANG</option>{locations.map(l=><option key={l.id_lokasi} value={l.id_lokasi}>{l.kode_lokasi} · {l.nama_lokasi}</option>)}</select></label>;
 const note=<label className="kavio-field material-wide"><span>KETERANGAN</span><input name="keterangan"/></label>;
 const footer=(disabled=false)=><KavioFormActions><button type="submit" className="kavio-button" disabled={disabled}>SIMPAN</button></KavioFormActions>;
 const selectedRequest=requestLines.filter(r=>r.id_permintaan===request&&(issueMode==='false'||bahan.some(m=>m.id_material===r.id_material)));
 const stock=(id:string,onlyBahan=false)=>spkStocks.filter(s=>s.id_spk===id&&(!onlyBahan||bahan.some(m=>m.id_material===s.id_material)));
 const limits=(rows:{id_material:string;jumlah:number}[])=>Object.fromEntries(rows.map(r=>[r.id_material,r.jumlah]));
 return <section className="material-actions"><div className="kavio-panel-head material-actions-head"><div><h2 className="kavio-panel-title">INPUT TRANSAKSI</h2><p className="kavio-panel-note">Satu transaksi dapat berisi banyak material. Tanggal mengikuti hari input.</p></div><span className="kavio-badge">TANPA BACKDATE</span></div>
 {mode==='saldo'?<KavioActionGate action="MATERIAL_WAREHOUSE_WRITE"><KavioTransactionModal title="Isi Stok Awal" focusIds={['receipt_material']}><form action={postMaterialReceipt} className="kavio-form material-form">{warehouseField()}<input type="hidden" name="saldo_awal" value="on"/><KavioMaterialLines materials={materials} withPrice/>{note}{footer(!locations.length||!materials.length)}</form></KavioTransactionModal></KavioActionGate>:<>
 <KavioActionGate action="MATERIAL_REQUEST_WRITE"><KavioTransactionModal title="Permintaan Material" focusIds={['request_spk']}><form action={createMaterialRequest} className="kavio-form material-form">{spkField()}<label className="kavio-field"><span>SUMBER LAPORAN</span><select name="sumber_laporan" defaultValue="MANDOR_PELAKSANA"><option value="MANDOR_PELAKSANA">MANDOR / PELAKSANA</option><option value="GUDANG">PETUGAS GUDANG</option></select></label><KavioMaterialLines materials={materials} quantityLabel="JUMLAH DIMINTA"/>{note}{footer(!spks.length||!materials.length)}</form></KavioTransactionModal></KavioActionGate>
 <KavioActionGate action="MATERIAL_WAREHOUSE_WRITE"><KavioTransactionModal title="Pemakaian Berdasarkan Permintaan" focusIds={['issue_request']}><form action={issueMaterialToSpk} className="kavio-form material-form"><label className="kavio-field material-wide"><span>PERMINTAAN</span><select name="id_permintaan" value={request} required onChange={e=>setRequest(e.target.value)}><option value="" disabled>PILIH PERMINTAAN</option>{Array.from(new Map(requestLines.map(r=>[r.id_permintaan,r])).values()).map(r=><option key={r.id_permintaan} value={r.id_permintaan}>{r.no_permintaan} · {labelSpk(r.id_spk)}</option>)}</select></label>{warehouseField()}<label className="kavio-field material-wide"><span>PEMENUHAN</span><select name="langsung_pakai" value={issueMode} onChange={e=>setIssueMode(e.target.value)}><option value="true">LANGSUNG JADI PEMAKAIAN AKTUAL (BAHAN)</option><option value="false">MASUK STOK SPK (BAHAN / ALAT)</option></select></label><KavioMaterialLines key={`${request}:${issueMode}`} materials={selectedRequest} limits={Object.fromEntries(selectedRequest.map(r=>[r.id_material,r.sisa]))} quantityLabel="JUMLAH DIPENUHI"/>{note}{footer(!request||!locations.length||!selectedRequest.length)}</form></KavioTransactionModal></KavioActionGate>
 <KavioActionGate action="MATERIAL_USE_WRITE"><KavioTransactionModal title="Pemakaian dari Gudang" focusIds={['direct_spk']}><form action={postDirectMaterialUsage} className="kavio-form material-form">{spkField()}{warehouseField()}<KavioMaterialLines materials={bahan} quantityLabel="JUMLAH PAKAI"/>{note}{footer(!spks.length||!locations.length||!bahan.length)}</form></KavioTransactionModal></KavioActionGate>
 <KavioActionGate action="MATERIAL_USE_WRITE"><KavioTransactionModal title="Pemakaian dari SPK" focusIds={['spk_usage_spk']}><form action={postSpkMaterialUsage} className="kavio-form material-form">{spkField('id_spk',{value:useSpk,change:setUseSpk})}<KavioMaterialLines key={useSpk} materials={stock(useSpk,true)} limits={limits(stock(useSpk,true))} quantityLabel="JUMLAH PAKAI"/>{note}{footer(!stock(useSpk,true).length)}</form></KavioTransactionModal></KavioActionGate>
 <KavioActionGate action="MATERIAL_WAREHOUSE_WRITE"><KavioTransactionModal title="Rekonsiliasi Sisa Stok" focusIds={['reconcile_spk']}><form action={reconcileSpkMaterial} className="kavio-form material-form">{spkField('id_spk',{value:reconcileSpk,change:setReconcileSpk})}<label className="kavio-field"><span>TINDAKAN</span><select name="tindakan" value={action} onChange={e=>setAction(e.target.value)}><option value="KEMBALI_KE_GUDANG">KEMBALI KE GUDANG</option><option value="PINDAH_KE_SPK">PINDAH KE SPK LAIN</option><option value="PEMAKAIAN_FINAL">PEMAKAIAN FINAL (BAHAN)</option><option value="HILANG_RUSAK">HILANG / RUSAK</option></select></label>{action==='KEMBALI_KE_GUDANG'&&warehouseField('id_lokasi_tujuan')}{action==='PINDAH_KE_SPK'&&spkField('id_spk_tujuan')}<KavioMaterialLines key={`${reconcileSpk}:${action}`} materials={stock(reconcileSpk,action==='PEMAKAIAN_FINAL')} limits={limits(stock(reconcileSpk,action==='PEMAKAIAN_FINAL'))} quantityLabel="JUMLAH DIREKONSILIASI"/><label className="kavio-field material-wide"><span>ALASAN {action==='HILANG_RUSAK'?'(WAJIB)':''}</span><input name="alasan" required={action==='HILANG_RUSAK'}/></label>{note}{footer(!stock(reconcileSpk,action==='PEMAKAIAN_FINAL').length)}</form></KavioTransactionModal></KavioActionGate>
 </>}
 </section>;
}
