import {deleteMaster} from '../delete-actions';
import KavioConfirmAction from '../../components/KavioConfirmAction';
import { redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';
import { createNotaris, toggleNotaris, updateNotaris } from './actions';
import KavioCreatePanel from '../../components/KavioCreatePanel';
import KavioFormModal from '../../components/KavioFormModal';
import KavioActionGate from '../../components/KavioActionGate';

type SearchParams=Promise<{error?:string;success?:string;edit?:string}>;
type Notaris={id_notaris:string;nama_notaris:string;no_izin:string|null;no_hp:string|null;alamat:string|null;status_aktif:boolean};

export default async function MasterNotarisPage({searchParams}:{searchParams:SearchParams}){
 const p=await searchParams; const supabase=await createClient();
const {data,error}=await supabase.from('master_notaris').select('id_notaris,nama_notaris,no_izin,no_hp,alamat,status_aktif').order('nama_notaris'); const rows=(data??[]) as Notaris[]; const editRow=p.edit?rows.find(r=>r.id_notaris===p.edit):null;
 return <main className="master-simple-page">
  {p.error??error?.message?<div className="kavio-alert error">{p.error??error?.message}</div>:null}{p.success?<div className="kavio-alert success">{p.success}</div>:null}
  <section className="kavio-panel"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">DAFTAR NOTARIS</h2><div className="kavio-panel-note">Notaris aktif yang dapat dipilih untuk proses akad.</div></div><span className="kavio-badge">{rows.length} DATA</span></div>
   <div className="kavio-table-wrap"><table className="kavio-table"><thead><tr><th>ID</th><th>NAMA</th><th>NO. IZIN</th><th>NO. HP</th><th>ALAMAT</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{rows.map(r=><tr key={r.id_notaris}><td className="master-highlight">{r.id_notaris}</td><td>{r.nama_notaris}</td><td>{r.no_izin||'—'}</td><td>{r.no_hp||'—'}</td><td>{r.alamat||'—'}</td><td><span className={`master-status ${r.status_aktif?'active':'inactive'}`}>{r.status_aktif?'AKTIF':'NONAKTIF'}</span></td><td><KavioActionGate action="MASTER_WRITE"><div className="kavio-master-row-actions"><a href={'/master/notaris?edit='+encodeURIComponent(r.id_notaris)} className="kavio-button secondary">EDIT</a><form action={toggleNotaris}><input type="hidden" name="id_notaris" value={r.id_notaris}/><input type="hidden" name="status_aktif" value={String(r.status_aktif)}/><button type="submit" className="kavio-button secondary">{r.status_aktif?'NONAKTIFKAN':'AKTIFKAN'}</button></form><KavioConfirmAction action={deleteMaster} label="HAPUS" confirmMessage="Hapus data master ini? Data yang digunakan tidak dapat dihapus." hidden={{master:'notaris',id_notaris:r.id_notaris}}/></div></KavioActionGate></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="kavio-empty">BELUM ADA DATA NOTARIS.</td></tr>}</tbody></table></div>
  </section>
  {editRow?<KavioActionGate action="MASTER_WRITE"><KavioFormModal open closeHref="/master/notaris" size="standard" ariaLabel="Edit Notaris" closeOnBackdrop={false} persistenceKey={`master-notaris-edit:${editRow.id_notaris}`}><section className="kavio-panel"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">EDIT NOTARIS — {editRow.id_notaris}</h2><div className="kavio-panel-note">ID notaris tetap. Data notaris dapat diperbarui.</div></div><a href="/master/notaris" className="kavio-button secondary">BATAL</a></div><form action={updateNotaris} className="kavio-form kavio-panel-body"><input type="hidden" name="id_notaris" value={editRow.id_notaris}/><label className="kavio-field"><span>ID NOTARIS</span><input value={editRow.id_notaris} readOnly/></label><label className="kavio-field"><span>NAMA NOTARIS</span><input name="nama_notaris" defaultValue={editRow.nama_notaris} required/></label><label className="kavio-field"><span>NO. IZIN</span><input name="no_izin" defaultValue={editRow.no_izin??''}/></label><label className="kavio-field"><span>NO. HP</span><input name="no_hp" defaultValue={editRow.no_hp??''}/></label><label className="kavio-field sales-span-2"><span>ALAMAT</span><input name="alamat" defaultValue={editRow.alamat??''}/></label><div className="kavio-actions"><button type="submit" className="kavio-button">SIMPAN PERUBAHAN</button></div></form></section></KavioFormModal></KavioActionGate>:null}
  <KavioCreatePanel formKey="master-notaris-create" buttonLabel="+ TAMBAH NOTARIS" title="INPUT NOTARIS BARU" note="Notaris diisi sebagai referensi proses akad Sales." badge="MASTER"><KavioActionGate action="MASTER_WRITE"><form action={createNotaris} className="kavio-form kavio-panel-body"><label className="kavio-field"><span>ID NOTARIS</span><input name="id_notaris" placeholder="NTR01" required/></label><label className="kavio-field"><span>NAMA NOTARIS</span><input name="nama_notaris" placeholder="Nama lengkap notaris" required/></label><label className="kavio-field"><span>NO. IZIN</span><input name="no_izin" placeholder="Nomor izin"/></label><label className="kavio-field"><span>NO. HP</span><input name="no_hp" placeholder="08xxxxxxxxxx"/></label><label className="kavio-field sales-span-2"><span>ALAMAT</span><input name="alamat" placeholder="Alamat kantor notaris"/></label><div className="kavio-actions"><button type="submit" className="kavio-button">SIMPAN NOTARIS</button></div></form></KavioActionGate></KavioCreatePanel>
 </main>;
}
