'use client';
import {submitBankGuaranteeClaim} from './actions';
import KavioActionGate from '../components/KavioActionGate';
import KavioTransactionModal from '../components/KavioTransactionModal';
import {ReceiptForm,Sale,Account} from './ReceiptEntryPanel';
import {formatKavioMoney} from '../lib/number-format';
type Guarantee={id_jaminan:string;id_sales:string;jenis_item:string;nominal_tagihan:number|string;status:string};
export default function BankGuaranteePanel({sales,items,accounts,received}:{sales:Sale[];items:Guarantee[];accounts:Account[];received:Record<string,number>}){
 return <section className="kavio-panel collection-actions"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">DANA JAMINAN</h2><div className="kavio-panel-note">Dana yang ditahan dicatat saat pencairan KPR. Ajukan ke bank, lalu catat penerimaannya bertahap atau sekaligus.</div></div></div>
 <div className="kavio-table-wrap"><table className="kavio-table"><thead><tr><th>KAVLING</th><th>KONSUMEN</th><th>ITEM</th><th>TAGIHAN</th><th>DITERIMA</th><th>SISA</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{items.map(item=>{const sale=sales.find(s=>s.id_sales===item.id_sales);const paid=received[item.id_jaminan]??0;const due=Number(item.nominal_tagihan)-paid;return <tr key={item.id_jaminan}><td>{sale?.id_kavling??'—'}</td><td>{sale?.nama_konsumen??'—'}</td><td>{item.jenis_item.replaceAll('_',' & ')}</td><td>{formatKavioMoney(item.nominal_tagihan)}</td><td>{formatKavioMoney(paid)}</td><td>{formatKavioMoney(due)}</td><td>{item.status.replaceAll('_',' ')}</td><td><KavioActionGate action="PAYMENT_RECEIPT_WRITE">{item.status==='BELUM_DIAJUKAN'?<form action={submitBankGuaranteeClaim} className="guarantee-claim-form"><input name="id_jaminan" type="hidden" value={item.id_jaminan}/><input name="tanggal_pengajuan" type="date" required aria-label="Tanggal pengajuan"/><button type="submit" className="kavio-button secondary">AJUKAN KE BANK</button></form>:due>0&&sale&&<KavioTransactionModal title="PENERIMAAN DANA JAMINAN" focusIds={[`guarantee_receipt:${item.id_jaminan}`]}><ReceiptForm sales={[sale]} accounts={accounts} focus={`guarantee_receipt:${item.id_jaminan}`} guarantee={{id_jaminan:item.id_jaminan,id_sales:item.id_sales,saldo:due}}/></KavioTransactionModal>}</KavioActionGate></td></tr>;})}{!items.length&&<tr><td colSpan={8} className="kavio-empty">BELUM ADA DANA JAMINAN. INPUT BERSAMA PENCAIRAN KPR.</td></tr>}</tbody></table></div></section>;
}
