import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '../../../../lib/supabase/server';
import { updateSalesInfo } from '../actions';
import { upsertKprProgress } from '../kpr-actions';

type SearchParams=Promise<{id?:string;error?:string;success?:string}>;
type Sale={id_sales:string;id_kavling:string;nama_konsumen:string;status_sales:string;jenis_pembayaran:string;id_bank:string|null;id_notaris:string|null;harga_jual:number|string|null;tgl_booking:string|null;target_akad:string|null;tgl_akad:string|null;status_aktif:boolean};
type Bank={id_bank:string;nama_bank:string}; type Notaris={id_notaris:string;nama_notaris:string}; type Kpr={id_progress:string;tahap:string;tanggal_update:string;keterangan:string|null};
const STAGES=[['KELENGKAPAN_DATA','KELENGKAPAN DATA'],['SURVEY_BANK','SURVEY BANK'],['INTERVIEW','INTERVIEW'],['SP3K','SP3K']] as const;
export default async function SalesDetailPage({searchParams}:{searchParams:SearchParams}){
 const p=await searchParams; const id=p.id; if(!id) redirect('/master/sales'); const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login');
 const [{data:sale,error:saleError},{data:banks},{data:notaries},{data:kpr}] = await Promise.all([supabase.from('sales').select('id_sales,id_kavling,nama_konsumen,status_sales,jenis_pembayaran,id_bank,id_notaris,harga_jual,tgl_booking,target_akad,tgl_akad,status_aktif').eq('id_sales',id).maybeSingle(),supabase.from('master_bank').select('id_bank,nama_bank').eq('status_aktif',true).order('nama_bank'),supabase.from('master_notaris').select('id_notaris,nama_notaris').eq('status_aktif',true).order('nama_notaris'),supabase.from('sales_kpr_progress').select('id_progress,tahap,tanggal_update,keterangan').eq('id_sales',id).order('tanggal_update')]);
 if(!sale) return <main className="master-simple-page"><div className="simple-alert error">{p.error??saleError?.message??'DATA SALES TIDAK DITEMUKAN'}</div><Link className="sales-secondary" href="/master/sales">KEMBALI KE SALES</Link></main>;
 const s=sale as Sale; const br=(banks??[]) as Bank[]; const nr=(notaries??[]) as Notaris[]; const kr=(kpr??[]) as Kpr[]; const kprMap=new Map(kr.map(x=>[x.tahap,x]));
 return <main className="master-simple-page"><div className="simple-head"><div><div className="simple-eyebrow">SALES DETAIL</div><h1>{s.id_kavling} — {s.nama_konsumen}</h1><p>Detail penjualan, bank KPR, informasi akad, dan tracking proses KPR.</p></div><Link className="sales-secondary" href="/master/sales">KEMBALI</Link></div>
 {p.error&&<div className="simple-alert error">{p.error}</div>}{p.success&&<div className="simple-alert success">{p.success}</div>}
 <section className="simple-card"><h2>DATA SALES</h2><form action={updateSalesInfo} className="simple-grid"><input type="hidden" name="id_sales" value={s.id_sales}/><label>STATUS SALES<select name="status_sales" defaultValue={s.status_sales}><option>BOOKING</option><option>DP</option><option value="PROSES_KPR">PROSES KPR</option><option>AKAD</option><option>BATAL</option></select></label><label>JENIS PEMBAYARAN<select name="jenis_pembayaran" defaultValue={s.jenis_pembayaran??''}><option>KPR</option><option>CASH</option><option>CASH_BERTAHAP</option></select></label><label>BANK KPR<select name="id_bank" defaultValue={s.id_bank??''}><option value="">PILIH BANK</option>{br.map(x=><option key={x.id_bank} value={x.id_bank}>{x.nama_bank}</option>)}</select></label><label>TARGET AKAD<input type="date" name="target_akad" defaultValue={s.target_akad??''}/></label><label>TANGGAL AKAD<input type="date" name="tgl_akad" defaultValue={s.tgl_akad??''}/></label><label>NOTARIS AKAD<select name="id_notaris" defaultValue={s.id_notaris??''}><option value="">PILIH NOTARIS</option>{nr.map(x=><option key={x.id_notaris} value={x.id_notaris}>{x.nama_notaris}</option>)}</select></label><div className="full action-end"><button type="submit">SIMPAN PERUBAHAN</button></div></form></section>
 {(s.jenis_pembayaran==='KPR'||s.status_sales==='PROSES_KPR')&&<section className="simple-card"><h2>PROGRESS PROSES KPR</h2><div style={{padding:'14px 16px'}}><div className="sales-kpr-grid">{STAGES.map(([key,label])=>{const row=kprMap.get(key);return <div key={key} className="simple-card" style={{margin:0,padding:'10px',background:row?'rgba(134,239,172,.06)':'rgba(255,255,255,.025)'}}><strong style={{fontSize:11}}>{label}</strong><div style={{marginTop:5,fontSize:10,color:'#C9BC99'}}>{row?row.tanggal_update:'BELUM UPDATE'}</div><div style={{marginTop:4,fontSize:10,color:'#C9BC99'}}>{row?.keterangan??'—'}</div></div>})}</div></div><form action={upsertKprProgress} className="simple-grid"><input type="hidden" name="id_sales" value={s.id_sales}/><label>TAHAP<select name="tahap" defaultValue="KELENGKAPAN_DATA">{STAGES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>TANGGAL UPDATE<input type="date" name="tanggal_update" required/></label><label className="full">KETERANGAN<textarea name="keterangan" rows={2} placeholder="Catatan proses KPR"/></label><div className="full action-end"><button type="submit">SIMPAN UPDATE KPR</button></div></form></section>}
 </main>
}
