import KavioFormActions from '../../components/KavioFormActions';
import {deleteMaster} from '../delete-actions';
import KavioConfirmAction from '../../components/KavioConfirmAction';
import KavioFormModal from '../../components/KavioFormModal';
import { redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';
import { upsertTemplateProgress } from './actions';
import KavioCreatePanel from '../../components/KavioCreatePanel';
import KavioActionGate from '../../components/KavioActionGate';

type SearchParams=Promise<{error?:string;success?:string;edit_tipe?:string;edit_kategori?:string}>;
type Tipe={id_tipe:string;nama_tipe:string}; type Kategori={id_kategori:string;nama_kategori:string;urutan:number}; type Template={id_tipe:string;id_kategori:string;bobot_standar:number|string};

export default async function TemplateProgressPage({searchParams}:{searchParams:SearchParams}){
 const p=await searchParams; const supabase=await createClient();
const [tipeRes,kategoriRes,templateRes]=await Promise.all([supabase.from('master_tipe_rumah').select('id_tipe,nama_tipe').eq('status_aktif',true).order('nama_tipe'),supabase.from('master_kategori_pekerjaan').select('id_kategori,nama_kategori,urutan').eq('status_aktif',true).order('urutan'),supabase.from('template_progress_tipe').select('id_tipe,id_kategori,bobot_standar').order('id_tipe').order('id_kategori')]);
 const tipeRows=(tipeRes.data??[]) as Tipe[]; const kategoriRows=(kategoriRes.data??[]) as Kategori[]; const templateRows=(templateRes.data??[]) as Template[]; const error=p.error??tipeRes.error?.message??kategoriRes.error?.message??templateRes.error?.message;
 const kategoriMap=new Map(kategoriRows.map(x=>[x.id_kategori,x.nama_kategori])); const grouped=new Map<string,Template[]>(); for(const row of templateRows) grouped.set(row.id_tipe,[...(grouped.get(row.id_tipe)??[]),row]);
 const edit=templateRows.find(r=>r.id_tipe===p.edit_tipe&&r.id_kategori===p.edit_kategori);
 return <main className="master-simple-page">
  {error?<div className="kavio-alert error">{error}</div>:null}{p.success?<div className="kavio-alert success">{p.success}</div>:null}
  <section className="kavio-panel"><div className="kavio-panel-head"><div><h2 className="kavio-panel-title">TEMPLATE PROGRESS PER TIPE RUMAH</h2><div className="kavio-panel-note">Bobot standar disimpan sebagai referensi dan akan disnapshot saat SPK dibuat.</div></div><span className="kavio-badge">{tipeRows.length} TIPE</span></div>
   <div className="kavio-table-wrap"><table className="kavio-table"><thead><tr><th>TIPE RUMAH</th><th>KATEGORI</th><th>BOBOT</th><th>AKSI</th></tr></thead><tbody>{tipeRows.map(tipe=>{const rows=grouped.get(tipe.id_tipe)??[]; return rows.length?rows.map(r=><tr key={`${r.id_tipe}-${r.id_kategori}`}><td>{tipe.id_tipe} — {tipe.nama_tipe}</td><td>{r.id_kategori} — {kategoriMap.get(r.id_kategori)??r.id_kategori}</td><td className="master-highlight">{(Number(r.bobot_standar)*100).toFixed(2)}%</td><td><KavioActionGate action="MASTER_WRITE"><div className="kavio-master-row-actions"><a className="kavio-button secondary" href={`/master/template-progress?edit_tipe=${encodeURIComponent(r.id_tipe)}&edit_kategori=${encodeURIComponent(r.id_kategori)}`}>EDIT</a><KavioConfirmAction action={deleteMaster} label="HAPUS" confirmMessage="Hapus bobot template ini? Total bobot perlu dilengkapi kembali." hidden={{master:'template-progress',id_tipe:r.id_tipe,id_kategori:r.id_kategori}}/></div></KavioActionGate></td></tr>):<tr key={`${tipe.id_tipe}-empty`}><td>{tipe.id_tipe} — {tipe.nama_tipe}</td><td colSpan={3} className="kavio-empty">BELUM ADA TEMPLATE.</td></tr>})}{!tipeRows.length&&<tr><td colSpan={4} className="kavio-empty">BELUM ADA TIPE RUMAH AKTIF.</td></tr>}</tbody></table></div>
  </section>
  <section className="master-template-total-grid">{tipeRows.map(tipe=>{const rows=grouped.get(tipe.id_tipe)??[];const total=rows.reduce((sum,row)=>sum+Number(row.bobot_standar),0)*100;const valid=Math.abs(total-100)<0.01;return <div key={tipe.id_tipe} className="master-template-total"><span>{tipe.nama_tipe}</span><span className={valid?'master-template-ok':'master-template-warn'}>{total.toFixed(2)}% {valid?'VALID':'PERLU DILENGKAPI'}</span></div>})}</section>
  <KavioCreatePanel formKey="master-template-progress" buttonLabel="+ TAMBAH / UBAH BOBOT" title="INPUT BOBOT TEMPLATE" note="Satu kombinasi tipe rumah + kategori. Total bobot per tipe idealnya 100%." badge="TEMPLATE"><KavioActionGate action="MASTER_WRITE"><form action={upsertTemplateProgress} className="kavio-form kavio-panel-body"><label className="kavio-field"><span>TIPE RUMAH</span><select name="id_tipe" defaultValue="" required><option value="" disabled>PILIH TIPE</option>{tipeRows.map(x=><option key={x.id_tipe} value={x.id_tipe}>{x.id_tipe} — {x.nama_tipe}</option>)}</select></label><label className="kavio-field"><span>KATEGORI PEKERJAAN</span><select name="id_kategori" defaultValue="" required><option value="" disabled>PILIH KATEGORI</option>{kategoriRows.map(x=><option key={x.id_kategori} value={x.id_kategori}>{x.id_kategori} — {x.nama_kategori}</option>)}</select></label><label className="kavio-field"><span>BOBOT STANDAR (%)</span><input name="bobot_standar" type="number" min="0" max="100" step="0.01" placeholder="15" required/></label><KavioFormActions><button type="submit" className="kavio-button">SIMPAN BOBOT</button></KavioFormActions></form></KavioActionGate></KavioCreatePanel>
 {edit&&<KavioActionGate action="MASTER_WRITE"><KavioFormModal open closeHref="/master/template-progress" ariaLabel="Edit bobot template" persistenceKey={`template-edit:${edit.id_tipe}:${edit.id_kategori}`}><section className="kavio-panel"><div className="kavio-panel-head"><h2>EDIT BOBOT TEMPLATE</h2></div><form action={upsertTemplateProgress} className="kavio-form kavio-panel-body"><input name="id_tipe" type="hidden" value={edit.id_tipe}/><input name="id_kategori" type="hidden" value={edit.id_kategori}/><p>{edit.id_tipe} · {kategoriMap.get(edit.id_kategori)}</p><label className="kavio-field"><span>BOBOT (%)</span><input name="bobot_standar" type="number" min="0" max="100" step="0.01" defaultValue={Number(edit.bobot_standar)*100} required/></label><KavioFormActions><button type="submit" className="kavio-button">SIMPAN BOBOT</button></KavioFormActions></form></section></KavioFormModal></KavioActionGate>}
 </main>;
}
